# Generated by Django 2.0 on 2018-04-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank_branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.CharField(max_length=100)),
                ('bank_id', models.IntegerField()),
                ('branch', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=400)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=400)),
            ],
        ),
    ]
